### ISSUE TITLE
Failed to Install

### ISSUE THREAD

**Issue by yonas124** [factrylabs/influx-opcua-server#1]
Hi factry, with node v12.2.0 I failed to install the module as below:

User@vps:~/influx-opcua-server$ sudo npm install                                                                                      > node-opcua-client@0.5.6 postinstall /home/user/influx-opcua-server/node_modules/node-opcua-client
> node test_helpers/create_certificates.js certificate -s -o certificates/client_selfsigned_cert_1024.pem

/home/user/influx-opcua-server/node_modules/yargs/yargs.js:1148
      else throw err
           ^

Error: EACCES: permission denied, mkdir '/home/user/influx-opcua-server/node_modules/node-opcua-client/certificates'
    at Object.mkdirSync (fs.js:761:3)
    at Object.mkdir (/home/user/influx-opcua-server/node_modules/node-opcua-pki/dist/lib/pki/toolbox.js:69:12)
    at readConfiguration (/home/user/influx-opcua-server/node_modules/node-opcua-pki/dist/lib/crypto_create_CA.js:149:15)
    at /home/user/influx-opcua-server/node_modules/node-opcua-pki/dist/lib/crypto_create_CA.js:554:34
    at /home/user/influx-opcua-server/node_modules/async/dist/async.js:3880:24
    at replenish (/home/user/influx-opcua-server/node_modules/async/dist/async.js:1011:17)
    at /home/user/influx-opcua-server/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/home/user/influx-opcua-server/node_modules/async/dist/async.js:1041:24)
    at /home/user/influx-opcua-server/node_modules/async/dist/async.js:1046:16
    at _parallel (/home/user/influx-opcua-server/node_modules/async/dist/async.js:3879:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-opcua-client@0.5.6 postinstall: `node test_helpers/create_certificates.js certificate -s -o certificates/client_selfsigned_cert_1024.pem`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-opcua-client@0.5.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-08-31T04_24_44_469Z-debug.log

Any idea what might went wrong?

**Comment by CodeByStella** [comment]
Hello @yonas124, @HogeBlekker, @coussej, @diericd, @vereecw,
I wanna contribute on this project. Please consider me. 
Thanks in advance.
